<?if(! eregi("(61.36.175|211.233.50.22|211.233.77)",$_SERVER['REMOTE_ADDR'])){?>
<?$Godo_P="http://211.233.50.2|godo.co.kr/webLogs|_Godo/webalizer";?>
<?if(! eregi("($Godo_P)",$_SERVER['HTTP_REFERER']) ){?>
<?if($_GET[hash]!=md5("godo_webhosting".$_SERVER['HTTP_HOST'])){?>
<?exit();}?>
<?}} ?>
<!-- Generated by The Webalizer  Ver. 2.23-05 -->
<!--                                          -->
<!-- Copyright 1997-2011  Bradford L. Barrett -->
<!--                                          -->
<!-- Distributed under the GNU GPL  Version 2 -->
<!--        Full text may be found at:        -->
<!--         http://www.webalizer.org         -->
<!--                                          -->
<!--  Give the power back to the programmers  -->
<!--   Support the Free Software Foundation   -->
<!--           (http://www.fsf.org)           -->
<!--                                          -->
<!-- *** Generated: 31-Jul-2016 02:02 KST *** -->

<HTML lang="ko">
<HEAD>
 <TITLE>사용량 통계: francosmith.com - 최종 12개월</TITLE>
</HEAD>

<BODY BGCOLOR="#E8E8E8" TEXT="#000000" LINK="#0000FF" VLINK="#FF0000">
<H2>사용량 통계: francosmith.com</H2>
<SMALL><STRONG>
최종 12개월<BR>
최종 갱신일 31-Jul-2016 02:02 KST<BR>
</STRONG></SMALL>
<CENTER>
<HR>
<P>
<IMG SRC="usage.png" ALT="Usage summary for francosmith.com" HEIGHT=256 WIDTH=512><P>
<TABLE WIDTH=600 BORDER=2 CELLSPACING=1 CELLPADDING=1>
<TR><TH HEIGHT=4></TH></TR>
<TR><TH COLSPAN=11 BGCOLOR="#C0C0C0" ALIGN=center>최종 12개월</TH></TR>
<TR><TH HEIGHT=4></TH></TR>
<TR><TH ALIGN=left ROWSPAN=2 BGCOLOR="#C0C0C0"><FONT SIZE="-1">월</FONT></TH>
<TH ALIGN=center COLSPAN=4 BGCOLOR="#C0C0C0"><FONT SIZE="-1">일 평균</FONT></TH>
<TH ALIGN=center COLSPAN=6 BGCOLOR="#C0C0C0"><FONT SIZE="-1">월 총계</FONT></TH></TR>
<TR><TH ALIGN=center BGCOLOR="#00805c"><FONT SIZE="-1">Hits</FONT></TH>
<TH ALIGN=center BGCOLOR="#0040ff"><FONT SIZE="-1">Files</FONT></TH>
<TH ALIGN=center BGCOLOR="#00e0ff"><FONT SIZE="-1">Pages</FONT></TH>
<TH ALIGN=center BGCOLOR="#ffff00"><FONT SIZE="-1">Visits</FONT></TH>
<TH ALIGN=center BGCOLOR="#ff8000"><FONT SIZE="-1">Sites</FONT></TH>
<TH ALIGN=center BGCOLOR="#ff0000"><FONT SIZE="-1">KBytes</FONT></TH>
<TH ALIGN=center BGCOLOR="#ffff00"><FONT SIZE="-1">Visits</FONT></TH>
<TH ALIGN=center BGCOLOR="#00e0ff"><FONT SIZE="-1">Pages</FONT></TH>
<TH ALIGN=center BGCOLOR="#0040ff"><FONT SIZE="-1">Files</FONT></TH>
<TH ALIGN=center BGCOLOR="#00805c"><FONT SIZE="-1">Hits</FONT></TH></TR>
<TR><TH HEIGHT=4></TH></TR>
<TR><TD NOWRAP><A HREF="usage_201607.php"><FONT SIZE="-1">Jul 2016</FONT></A></TD>
<TD ALIGN=right><FONT SIZE="-1">24091</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">11545</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">2706</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">264</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">2713</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">9811618</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">7926</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">81205</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">346353</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">722753</FONT></TD></TR>
<TR><TD NOWRAP><A HREF="usage_201606.php"><FONT SIZE="-1">Jun 2016</FONT></A></TD>
<TD ALIGN=right><FONT SIZE="-1">20420</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">8883</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">2355</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">242</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">2244</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">7911707</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">7289</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">70659</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">266519</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">612612</FONT></TD></TR>
<TR><TD NOWRAP><A HREF="usage_201605.php"><FONT SIZE="-1">May 2016</FONT></A></TD>
<TD ALIGN=right><FONT SIZE="-1">24996</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">9103</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">2700</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">247</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">2343</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">7952137</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">7663</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">83707</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">282203</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">774888</FONT></TD></TR>
<TR><TD NOWRAP><A HREF="usage_201604.php"><FONT SIZE="-1">Apr 2016</FONT></A></TD>
<TD ALIGN=right><FONT SIZE="-1">16749</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">9391</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">1996</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">243</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">2045</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">7662491</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">7319</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">59904</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">281759</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">502494</FONT></TD></TR>
<TR><TD NOWRAP><A HREF="usage_201603.php"><FONT SIZE="-1">Mar 2016</FONT></A></TD>
<TD ALIGN=right><FONT SIZE="-1">18906</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">11589</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">2069</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">236</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">2120</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">9310200</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">7319</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">64144</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">359272</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">586093</FONT></TD></TR>
<TR><TD NOWRAP><A HREF="usage_201602.php"><FONT SIZE="-1">Feb 2016</FONT></A></TD>
<TD ALIGN=right><FONT SIZE="-1">22336</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">13480</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">2065</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">218</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">2061</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">10758103</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">6325</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">59886</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">390942</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">647752</FONT></TD></TR>
<TR><TD NOWRAP><A HREF="usage_201601.php"><FONT SIZE="-1">Jan 2016</FONT></A></TD>
<TD ALIGN=right><FONT SIZE="-1">16885</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">8218</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">1864</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">210</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">2108</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">7944685</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">6520</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">57805</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">254772</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">523457</FONT></TD></TR>
<TR><TD NOWRAP><A HREF="usage_201512.php"><FONT SIZE="-1">Dec 2015</FONT></A></TD>
<TD ALIGN=right><FONT SIZE="-1">17848</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">8837</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">1905</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">187</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">1966</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">8043783</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">5827</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">59067</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">273976</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">553300</FONT></TD></TR>
<TR><TD NOWRAP><A HREF="usage_201511.php"><FONT SIZE="-1">Nov 2015</FONT></A></TD>
<TD ALIGN=right><FONT SIZE="-1">19078</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">8858</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">2034</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">157</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">759</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">3348335</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">2211</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">28483</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">124019</FONT></TD>
<TD ALIGN=right><FONT SIZE="-1">267104</FONT></TD></TR>
<TR><TH HEIGHT=4></TH></TR>
<TR><TH BGCOLOR="#C0C0C0" COLSPAN=6 ALIGN=left><FONT SIZE="-1">총계</FONT></TH>
<TH BGCOLOR="#C0C0C0" ALIGN=right><FONT SIZE="-1">72743059</FONT></TH>
<TH BGCOLOR="#C0C0C0" ALIGN=right><FONT SIZE="-1">58399</FONT></TH>
<TH BGCOLOR="#C0C0C0" ALIGN=right><FONT SIZE="-1">564860</FONT></TH>
<TH BGCOLOR="#C0C0C0" ALIGN=right><FONT SIZE="-1">2579815</FONT></TH>
<TH BGCOLOR="#C0C0C0" ALIGN=right><FONT SIZE="-1">5190453</FONT></TH></TR>
<TR><TH HEIGHT=4></TH></TR>
</TABLE>
</CENTER>
<P>
<HR>
<TABLE WIDTH="100%" CELLPADDING=0 CELLSPACING=0 BORDER=0>
<TR>
<TD ALIGN=left VALIGN=top>
<SMALL>Generated by
<A HREF="http://www.webalizer.org/"><STRONG>Webalizer Version 2.23</STRONG></A>
</SMALL>
</TD>
</TR>
</TABLE>

<!-- Webalizer Version 2.23-05 (Mod: 14-Apr-2011) -->

</BODY>
</HTML>
